import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ulises Baretta</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Ulises Baretta
          </h1>
          <p className="text-2xl text-white"> Full Stack Developer</p>
          <div className="flex grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/about"
            >
              <h3 className="text-2xl font-bold">Sobre mí </h3>
              <div className="text-lg">
                Quíen soy y cuáles son mis habilidades y conocimientos
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/proyectos"
            >
              <h3 className="text-2xl font-bold">Projectos </h3>
              <div className="text-lg">
                Mi experiencia en el mundo del desarrollo web
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/redes"
            >
              <h3 className="text-2xl font-bold">Redes y CV </h3>
              <div className="text-lg">
                Mis redes sociales para que puedas contactarme
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
