import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

export default function Projectos() {
  return (
    <>
      <Head>
        <title>Proyects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Proyectos
          </h1>
        <div className="flex max-w-md flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
          <div className="text-lg">
            He creado algunos proyectos pequeños para practicar y aprender,
            algunos de ellos son:
            <ul className="list-inside list-disc">
              <li>
                <Link href="https://github.com/ulisao/twitt3r">
                  Clon de Twitter creado con T3 Stack
                </Link>
              </li>
              <li>
                <Link href="https://github.com/ulisao/Api-de-usuario">
                  Api de creación de usuarios hecho con Django Rest Framework
                </Link>
              </li>
              <li>
                <Link href="https://github.com/ulisao/bloag-avanz-drf-react">
                  Blog creado con Django Rest Framework y React
                </Link>
              </li>
              <p>
                Actualmente estoy trabajando en mi propia academia online para
                aprender a programar. Mi objetivo es crear un espacio de
                aprendizaje moderno y comodo para todos.
              </p>
            </ul>
          </div>
        </div>
        <Link
              className="p-4 text-white"
              href="/"
            >
              <h3 className="text-2xl font-bold">  Volver </h3>
          </Link>
      </div>
      </main>
    </>
  );
}
